### ISSUE TITLE
agnosc compiler error

### ISSUE THREAD

**Issue by miksovic** [tomerfiliba/agnos#40]
when running agnosc.bat get the following error message - syntax of python has been changed from 'Exception, ex' to 'Exception as ex'.

File "agnosc", line 94
    except Exception, ex:
SyntaxError: invalid syntax

**Comment by tomerfiliba** [comment]
i assume you're using python 3.xx? agnos was designed for python 2.5-2.7, future versions will add python 3 support.

i think, though, that running the 2to3.py script (shipped along with python 3 installer, in the scripts directory) would solve it... i don't suppose agnos uses any "low level" python features.

**Comment by tomerfiliba** [comment]
miksovic -- it should all work now. please try running it again.
(not yet on sourceforge, v1.0.2 will be released within two weeks)

**Comment by miksovic** [comment]
Great, cheers!
