### ISSUE TITLE
C++ agnolib build 

### ISSUE THREAD

**Issue by miksovic** [tomerfiliba/agnos#41]
When trying to build c++ agnolib visual studio solution following errors have been thrown.

configuration
windows 7, VS2010, boost_1_46_1

<pre><code>
Error   23  error C2761: 'unpack' : member function redeclaration not allowed   c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 214 1   agnos_library
Error   12  error C2660: 'fclose' : function does not take 0 arguments  c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\servers.cpp 115 1   agnos_library
Error   10  error C2589: '(' : illegal token on right side of '::'  c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\servers.cpp 115 1   agnos_library
Error   3   error C2512: 'std::basic_istream<_Elem,_Traits>' : no appropriate default constructor available c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\transports.cpp  96  1   agnos_library
Error   26  error C2447: '{' : missing function header (old-style formal list?) c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 215 1   agnos_library
Error   1   error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   2   error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   6   error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   7   error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   14  error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   17  error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   28  error C2371: 'int8_t' : redefinition; different basic types c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\objtypes.hpp    44  1   agnos_library
Error   22  error C2146: syntax error : missing ')' before identifier 'obj' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 214 1   agnos_library
Error   25  error C2143: syntax error : missing ';' before '{'  c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 215 1   agnos_library
Error   11  error C2143: syntax error : missing ')' before '::' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\servers.cpp 115 1   agnos_library
Error   21  error C2065: '_Bit_reference' : undeclared identifier   c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 214 1   agnos_library
Error   9   error C2061: syntax error : identifier '_Bit_reference' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   16  error C2061: syntax error : identifier '_Bit_reference' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   19  error C2061: syntax error : identifier '_Bit_reference' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   30  error C2061: syntax error : identifier '_Bit_reference' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   13  error C2059: syntax error : ')' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\servers.cpp 115 1   agnos_library
Error   24  error C2059: syntax error : ')' c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 214 1   agnos_library
Error   8   error C2039: '_Bit_reference' : is not a member of 'std'    c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   15  error C2039: '_Bit_reference' : is not a member of 'std'    c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   18  error C2039: '_Bit_reference' : is not a member of 'std'    c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
Error   20  error C2039: '_Bit_reference' : is not a member of 'std'    c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.cpp 214 1   agnos_library
Error   29  error C2039: '_Bit_reference' : is not a member of 'std'    c:\users\michal\desktop\tomerfiliba-agnos-v1.0.0-11-gec00972\tomerfiliba-agnos-ec00972\libagnos\cpp\src\packers.hpp 168 1   agnos_library
</code></pre>

**Comment by tomerfiliba** [comment]
turns out C++ is so ill-defined that even platform-agnostic code won't cross-compile without some ifdefs...
closed by 8d00e22485fed5acb654a5c5c54b38cf518286f7
