### ISSUE TITLE
Date Type documentation is incorrect

### ISSUE THREAD

**Issue by davidsj2** [tomerfiliba/agnos#53]
http://agnos.sourceforge.net/userguide/types.html#doc-types

Documentation states that "datetime" is used in the IDL to represent a date.  Attempting to use datetime results in the following error: 
agnos_compiler.idl_syntax.IDLError: unknown type 'datetime'

I believe the correct date type is simply "date".

**Comment by tomerfiliba** [comment]
@davidsj2 - thanks!
